# Generated by Django 6.0.7 on 2026-08-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AddField(
            model_name='project',
            name='icon',
            field=models.CharField(choices=[('code', 'Код'), ('chat', 'Сообщение'), ('list', 'Список'), ('star', 'Звезда'), ('folder', 'Папка'), ('gear', 'Шестерёнка'), ('user', 'Пользователь'), ('globe', 'Глобус')], default='code', max_length=20, verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядок (меньше = выше)'),
        ),
    ]
